export const meta = {
  name: 'dahilg-gameplay-diagnose',
  description: 'Root-cause 4 broken Da Hilg gameplay issues (T-pose anim, giant nibblers, broken attach mechanic, HUD layout) into concrete fix specs',
  phases: [
    { title: 'Diagnose', detail: '4 parallel root-cause lenses' },
    { title: 'Synthesize', detail: 'one implementable fix list' },
  ],
}

const RT = '/Users/mcohen/dev/home/unity/DaHilgUnity/Assets/DaHilg/Scripts/Runtime'
const ED = '/Users/mcohen/dev/home/unity/DaHilgUnity/Assets/DaHilg/Scripts/Editor'
const CTX = [
  'Da Hilg = Unity 6000.5 WebGL game (Built-in RP). A real-device + local screenshot shows MULTIPLE broken things. The user recently refactored in parallel: "single-surface levels (all + XQ)" + "URP rendering" material code + "windows scale with wall size" (commits 58692ffb,4f48616f,383496b5,742ef06d,037f35be). That refactor may have broken the character/animation/nibbler systems. Verify against the ACTUAL code.',
  'SYMPTOM 1 (animation): the PLAYER (Cece) and the NPCs all render with arms straight out horizontally (a T-POSE / bind pose) instead of idling, walking, or running. The user reads this as "emoting constantly". They want: characters use a standard locomotion rig when moving; the PLAYER emotes ONLY on explicit input or as a reaction to being attacked — never ambient. So the real bug is likely that NO locomotion/idle clip is playing (T-pose) — the Animator has no/broken clips. Note Settings/GeneratedAnimations/ is gitignored + regenerated by the build (DaHilgProjectBuilder ValidateCharacterAnimationAssets / RebuildUnityScene).',
  'SYMPTOM 2 (giant nibblers): some nibblers render BUILDING-TALL and far from the camera (one is "through the ground to its waist, taller than the whole building"). Code claims Root.localScale = Vector3.one * scale with scale = Settings.NibblerScale (~0.32), so something is overriding scale OR the skinned-mesh/rig/rootbone renders huge OR a parent transform is scaled. This is NOT the near-camera-proximity case (there is already a hide-within-1.8m fix); these giants are FAR. Find the REAL scale/rig cause.',
  'SYMPTOM 3 (core mechanic broken/unverified): nibblers are supposed to chase, LUNGE, climb, and ATTACH (ride on the body) and overwhelm the player, who flops/rolls to escape. The screenshot shows "26 riders / MARKED" but no nibblers visibly on the player. Trace the FSM (DaHilgNibblerAgent chase->Windup->Lunge->Climb->Attached) + the lunge/attach gates + PositionOnBody + the overwhelm system, and find why nibblers may not actually be visibly jumping on + clinging to the player (e.g., attach anchors off-body, lunge whiffing always, attached ones hidden by the camera-occlusion fix, scale making attach math wrong).',
  'SYMPTOM 4 (HUD layout): the user explicitly wants — a SMALLER status panel in the UPPER-LEFT, the MINIMAP in the UPPER-RIGHT (it is currently upper-LEFT under the panel), and compact COLLAPSIBLE controls elsewhere. Current DaHilgHud puts the panel upper-left (too big) + minimap under it (upper-left) + a segmented bar upper-right. Map the current layout and give the exact RefreshResponsiveControls/SetPanelFrame changes to hit the spec on desktop AND phone with no overlap.',
  'KEY FILES:',
  RT + '/DaHilgActor.cs  (locomotion/idle/emote animation: UpdateLocomotionAnimation, PlayAnim, PlayEmote role guard, StepMotion)',
  RT + '/DaHilgNibblerAgent.cs  (scale in ctor/Spawn/Scatter/Crush, FSM chase/Windup/Lunge/Climb/Attached, PositionOnBody, ChooseAttachAnchor, camera-occlusion hide)',
  RT + '/DaHilgGameManager.cs  (BuildNibblerPool scale + pool, TickNibblers spawn/overwhelm/struggle, m_NibblerRoot)',
  RT + '/DaHilgHud.cs  (RefreshResponsiveControls, SetPanelFrame, BuildTopPanel, BuildMinimap, the segmented compact bar, collapse)',
  ED + '/DaHilgProjectBuilder.cs  (RebuildUnityScene, BuildAnimatorControllers/BuildAnimalControllers, ValidateCharacterAnimationAssets, character prefab + nibbler setup, GeneratedAnimations)',
  '/Users/mcohen/dev/home/unity/DaHilgUnity/Assets/DaHilg/Settings/  (DaHilgGameSettings.asset NibblerScale, the *Controllers/*.controller animator controllers, GeneratedAnimations/)',
  'Also run `git log --oneline -8` + `git show --stat` on the recent refactor commits to see if they touched characters/anims/nibbler scale.',
].join('\n')

const FIND_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['lens', 'rootCause', 'evidence', 'fix', 'fileLocations', 'confidence'],
  properties: {
    lens: { type: 'string' },
    rootCause: { type: 'string', description: 'the concrete root cause, grounded in code' },
    evidence: { type: 'string', description: 'file:line + reasoning that proves it' },
    fix: { type: 'string', description: 'exact, implementable fix (code/values/locations)' },
    fileLocations: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'string', enum: ['low', 'medium', 'high'] },
  },
}

const SYNTH_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['fixes', 'verifyPlan'],
  properties: {
    fixes: { type: 'array', minItems: 4, items: { type: 'object', additionalProperties: false,
      required: ['rank', 'title', 'file', 'change', 'why'],
      properties: { rank: { type: 'integer' }, title: { type: 'string' }, file: { type: 'string' }, change: { type: 'string' }, why: { type: 'string' } } } },
    verifyPlan: { type: 'array', items: { type: 'string', description: 'how to verify each fix in-engine' } },
  },
}

phase('Diagnose')
const LENSES = [
  { key: 'anim-tpose', focus: 'Why do the player + NPCs render in T-pose/arms-out instead of locomotion/idle? Is the Animator missing clips (GeneratedAnimations not regenerated / broken by the refactor), is the controller wrong, did the single-surface/URP refactor break the rig or clip wiring? Also confirm the player emote role-guard is correct (only on input/attack). Give the exact fix to restore locomotion + idle + correct emote-only-on-input.' },
  { key: 'giant-scale', focus: 'Why do some nibblers render BUILDING-TALL far from the camera? Trace EVERY scale influence: Settings.NibblerScale value, BuildNibblerPool scale arg, Root.localScale writes, m_NibblerRoot/parent scale, the character prefab root + rootbone scale, SkinnedMeshRenderer bounds/updateWhenOffscreen, the controller height vs visual. Find the REAL cause of a huge-scale nibbler (this is separate from the near-camera hide). Give the exact fix.' },
  { key: 'core-mechanic', focus: 'Does the chase->Windup->Lunge->Climb->Attached FSM actually put nibblers visibly ON the player, clinging, overwhelming, with flop/roll escape? Find why they may not (lunge always whiffing, attach anchors off-body, attached ones hidden by the camera-occlusion fix at <1.8m so you never SEE them on you, scale breaking attach distance math, overwhelm not triggering). The user demands: nibblers visibly jump on + cling, player flops to escape. Give the exact fix to make the swarm visibly attack + cling.' },
  { key: 'hud-layout', focus: 'Re-layout the HUD to the spec: SMALLER status panel upper-LEFT, MINIMAP upper-RIGHT (move it from upper-left), compact COLLAPSIBLE controls elsewhere (the segmented VIEW/PLAYER/LEVEL/MENU bar). Give exact RefreshResponsiveControls/SetPanelFrame/BuildMinimap changes for desktop + phone, no overlap.' },
]
const findings = (await parallel(LENSES.map(L => () => agent(
  'You are a Unity gameplay engineer doing focused ROOT-CAUSE analysis of ONE broken thing, grounded in the actual code (read the files). Be concrete: exact cause, file:line evidence, and an implementable fix.\n\nFOCUS: ' + L.focus + '\n\nCONTEXT:\n' + CTX,
  { label: 'diag:' + L.key, phase: 'Diagnose', schema: FIND_SCHEMA }
)))).filter(Boolean)
log('Diagnosis done: ' + findings.length + ' lenses. Synthesizing.')

phase('Synthesize')
const synth = await agent(
  'Synthesize these 4 root-cause diagnoses into ONE prioritized, directly-implementable fix list (file + exact change + why) plus an in-engine verify plan for each. Order by player impact: locomotion/T-pose + giant-nibbler + visible attach mechanic first, HUD layout last.\n\n=== DIAGNOSES ===\n' + JSON.stringify(findings, null, 1) + '\n\n=== CONTEXT ===\n' + CTX,
  { label: 'synthesize', phase: 'Synthesize', schema: SYNTH_SCHEMA }
)

return { findings, synth }
